services:
  pooh:
    image: itzg/minecraft-server
    ports:
      - target: 25565
        published: 25565
        protocol: tcp
        mode: host
    environment:
      EULA: "TRUE"
      VERSION: "1.21.1"
      TYPE: "PAPER"
      MEMORY: "1G"
      TZ: "Europe/Berlin"
      SERVER_PORT: "25565"
      ONLINE_MODE: "FALSE"
    volumes:
      - type: bind
        source: ./data
        target: /data/plugins
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: mydb

  adminer:
    image: adminer
    restart: always
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    depends_on:
      - db